name: A workflow for my Hello World file
on: push
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run on the project setup.
        run: ./toolchain/build.sh
